import { Gender } from './gender.enum';
import { HebrewWord } from './hebrew-word';

export const WORDS: HebrewWord[] = [
  {
    english: 'EXAMPLE',
    hebrew: 'אאא',
    pronunciation: 'xxx',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Day',
    hebrew: 'יוֹם',
    pronunciation: 'yome',
    transliteration: 'yôm',
    gender: Gender.masculine,
    strongsNumber: 'H3117',
  },
  {
    english: 'Judge',
    hebrew: 'שָׁפַט',
    pronunciation: "shaw-fat'",
    transliteration: 'šāp̄aṭ',
    gender: Gender.masculine,
    strongsNumber: 'H8199',
  },
  {
    english: 'Famine/Hunger',
    hebrew: 'רָעָב',
    pronunciation: "raw-awb'",
    transliteration: 'rāʿāḇ',
    gender: Gender.masculine,
    strongsNumber: 'H7458',
  },
  {
    english: 'Land/Earth',
    hebrew: 'אֶרֶץ',
    pronunciation: "eh'-rets",
    transliteration: "'ereṣ",
    gender: Gender.masculine,
    strongsNumber: 'H776',
  },
  {
    english: 'Man',
    hebrew: 'אִישׁ',
    pronunciation: 'eesh',
    transliteration: "'îš",
    gender: Gender.masculine,
    strongsNumber: 'H376',
  },
  {
    english: 'Woman',
    hebrew: 'אִשָּׁה',
    pronunciation: "ish-shaw'",
    transliteration: "'iššâ",
    gender: Gender.feminine,
    strongsNumber: 'H802',
  },
  {
    english: 'Name',
    hebrew: 'שם',
    pronunciation: 'shem',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'There',
    hebrew: 'שם',
    pronunciation: 'sham',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Son',
    hebrew: 'בן',
    pronunciation: 'ben',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'House/Household',
    hebrew: 'בות',
    pronunciation: 'beyt',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Field',
    hebrew: 'שדה',
    pronunciation: 'sadeh',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Bread',
    hebrew: 'לחם',
    pronunciation: 'lekhem',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'God',
    hebrew: 'אל',
    pronunciation: 'El',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'To',
    hebrew: 'אל',
    pronunciation: '??',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Bride',
    hebrew: 'כלה',
    pronunciation: 'kalah',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'King',
    hebrew: 'מלך',
    pronunciation: 'melekh',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Queen',
    hebrew: 'מלכה',
    pronunciation: 'melkhah',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Year',
    hebrew: 'שנה',
    pronunciation: 'shanah',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Child',
    hebrew: 'ילד',
    pronunciation: 'yeled',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'People',
    hebrew: 'עם',
    pronunciation: 'ahm',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Place',
    hebrew: 'מקום',
    pronunciation: 'makhom',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Path',
    hebrew: 'דרך',
    pronunciation: 'derekh',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Mother',
    hebrew: 'אמה',
    pronunciation: 'eemmah',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Refuge',
    hebrew: 'הסה',
    pronunciation: 'khasah',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Compassion',
    hebrew: 'חסד',
    pronunciation: 'khased',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
  {
    english: 'Comfort',
    hebrew: 'נוח',
    pronunciation: 'noakh',
    transliteration: '',
    gender: Gender.feminine,
    strongsNumber: 'H000',
  },
  {
    english: 'Kiss/Weapon',
    hebrew: 'נשק',
    pronunciation: 'nesheq',
    transliteration: '',
    gender: Gender.masculine,
    strongsNumber: 'H000',
  },
];
