import { Gender } from './gender.enum';
import { HebrewWord } from './hebrew-word';
import { SpeechType } from './speech-type.enum';

export const WORDS: HebrewWord[] = [
  // {
  //   english: 'EXAMPLE',
  //   hebrew: 'אאא',
  //   pronunciation: 'xxx',
  //   transliteration: '',
  //   gender: Gender.masculine,
  //   speech: SpeechType.noun,
  //   strongsNumber: 'H000',
  // },
  {
    english: 'Day',
    hebrew: 'יוֹם',
    pronunciation: 'yome',
    transliteration: 'yôm',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H3117',
  },
  {
    english: 'Judge',
    hebrew: 'שָׁפַט',
    pronunciation: "shaw-fat'",
    transliteration: 'šāp̄aṭ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H8199',
  },
  {
    english: 'Famine/Hunger',
    hebrew: 'רָעָב',
    pronunciation: "raw-awb'",
    transliteration: 'rāʿāḇ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H7458',
  },
  {
    english: 'Land/Earth',
    hebrew: 'אֶרֶץ',
    pronunciation: "eh'-rets",
    transliteration: "'ereṣ",
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H776',
  },
  {
    english: 'Man',
    hebrew: 'אִישׁ',
    pronunciation: 'eesh',
    transliteration: "'îš",
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H376',
  },
  {
    english: 'Woman',
    hebrew: 'אִשָּׁה',
    pronunciation: "ish-shaw'",
    transliteration: "'iššâ",
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H802',
  },
  {
    english: 'Name',
    hebrew: 'שֵׁם',
    pronunciation: 'shame',
    transliteration: 'šēm',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H8034',
  },
  {
    english: 'There',
    hebrew: 'שָׁם',
    pronunciation: 'shawm',
    transliteration: 'šām',
    gender: Gender.masculine,
    speech: SpeechType.adverb,
    strongsNumber: 'H8033',
  },
  {
    english: 'Son',
    hebrew: 'בֵּן',
    pronunciation: 'bane',
    transliteration: 'bēn',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H1123',
  },
  {
    english: 'House/Household',
    hebrew: 'בַּיִת',
    pronunciation: "bah'-yith",
    transliteration: 'bayiṯ',
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H1004',
  },
  {
    english: 'Field',
    hebrew: 'שָׂדֶה',
    pronunciation: "saw-deh'",
    transliteration: 'śāḏê',
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H7704',
  },
  {
    english: 'Bread',
    hebrew: 'לֶחֶם',
    pronunciation: "lekh'-em",
    transliteration: 'leḥem',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H3899',
  },
  {
    english: 'God',
    hebrew: 'אֵל',
    pronunciation: 'ale',
    transliteration: "'ēl",
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H410',
  },
  {
    english: 'To',
    hebrew: 'אֵל',
    pronunciation: 'ale',
    transliteration: "'ēl",
    gender: Gender.na,
    speech: SpeechType.preposition,
    strongsNumber: 'H413',
  },
  {
    english: 'Bride',
    hebrew: 'כַּלָּה',
    pronunciation: "kal-law'",
    transliteration: 'kallâ',
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H3618',
  },
  {
    english: 'King',
    hebrew: 'מֶלֶךְ',
    pronunciation: "meh'-lek",
    transliteration: 'meleḵ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H4430',
  },
  {
    english: 'Queen',
    hebrew: 'מַלְכָּה',
    pronunciation: "mal-kaw'",
    transliteration: 'malkâ',
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H4436',
  },
  {
    english: 'Year',
    hebrew: 'שָׁנָה',
    pronunciation: "shaw-neh'",
    transliteration: 'šānâ',
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H8141',
  },
  {
    english: 'Child',
    hebrew: 'יֶלֶד',
    pronunciation: "yeh'-led",
    transliteration: 'yeleḏ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H3206',
  },
  {
    english: 'People',
    hebrew: 'עַם',
    pronunciation: 'am',
    transliteration: 'ʿam',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H5971',
  },
  {
    english: 'Place',
    hebrew: 'מָקוֹם',
    pronunciation: "maw-kome'",
    transliteration: 'māqôm',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H4725',
  },
  {
    english: 'Path',
    hebrew: 'דֶּרֶךְ',
    pronunciation: "deh'-rek",
    transliteration: 'dereḵ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H1870',
  },
  {
    english: 'Mother',
    hebrew: '(אֵם) אמה',
    pronunciation: 'eemmah (ame)',
    transliteration: "??? ('ēm)",
    gender: Gender.feminine,
    speech: SpeechType.noun,
    strongsNumber: 'H517',
    notes:
      'The strongs entry and the first mention (in parenthesis) does not show the word as we learned in class.',
  },
  {
    english: 'Refuge',
    hebrew: 'חָסָה',
    pronunciation: "khaw-saw'",
    transliteration: 'ḥāsâ',
    gender: Gender.na,
    speech: SpeechType.verb,
    strongsNumber: 'H2620',
  },
  {
    english: 'Compassion',
    hebrew: 'חֶסֶד',
    pronunciation: "kheh'-sed",
    transliteration: 'ḥeseḏ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H2617',
  },
  {
    english: 'Comfort',
    hebrew: 'נוּחַ',
    pronunciation: "noo'-akh",
    transliteration: 'nûaḥ',
    gender: Gender.masculine,
    speech: SpeechType.noun,
    strongsNumber: 'H5118',
  },
  {
    english: 'Kiss/Weapon',
    hebrew: 'נָשַׁק',
    pronunciation: "naw-shak'",
    transliteration: 'nāšaq',
    gender: Gender.na,
    speech: SpeechType.verb,
    strongsNumber: 'H5401',
  },
];
